# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_desc',
            field=models.CharField(default='good_job', max_length=32),
            preserve_default=False,
        ),
    ]
