# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoramlCourse',
            new_name='NormalCourse',
        ),
    ]
