# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_auto_20190811_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='content_type',
            new_name='content_typee',
        ),
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='object_id',
            new_name='object_idd',
        ),
    ]
